name: deploy-workflow
on:
  push:
    branches:
     - main
jobs:
  deploy-homepage-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          persist-credentials: false
      - name: install and build
        run: |
          npm install
          npm run build
      - name: start deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with: 
            branch: deploy
            folder: dist
            
